# Generated by Django 3.1.7 on 2021-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210515_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
