# Generated by Django 3.1.7 on 2021-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
