# Generated by Django 3.1.7 on 2021-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210520_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
