# Generated by Django 3.1.7 on 2021-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210522_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
