# Generated by Django 3.1.7 on 2021-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210608_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
