# Generated by Django 3.1.7 on 2021-06-09 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210608_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
