# Generated by Django 3.1.7 on 2021-06-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210610_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='comments',
            new_name='comment',
        ),
    ]
