# Generated by Django 3.1.7 on 2021-06-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210613_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='startingPrice',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
