# Generated by Django 3.2.5 on 2021-08-26 17:50

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210826_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 26, 17, 50, 39, 881812)),
        ),
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
