# Generated by Django 3.2.5 on 2021-08-26 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20210826_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creationTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 26, 19, 42, 9, 260487)),
        ),
    ]
